Models/ErrorViewModel.cs
using System;

namespace TaskListMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TaskListContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace TaskListMVC.Models
{
    public partial class TaskListContext : DbContext
    {
        public TaskListContext()
        {
        }

        public TaskListContext(DbContextOptions<TaskListContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ToDoItems> ToDoItems { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

                optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=TaskList;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ToDoItems>(entity =>
            {
                entity.Property(e => e.AssignedEmployee).HasMaxLength(25);

                entity.Property(e => e.DueDate).HasColumnType("date");

                entity.Property(e => e.ItemDescription).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Models/ToDoItems.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace TaskListMVC.Models
{
    public partial class ToDoItems
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Description")]
        public string ItemDescription { get; set; }
        [Required]
        //[Range(typeof(DateTime), DateTime.Today.ToString(), DateTime.Now.AddYears(20).ToString())]
        [DisplayName("Due Date")]
        //[DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DueDate { get; set; }
        public bool? Progress { get; set; } = false;
        [DisplayName("Employee")]
        [Required]
        public string AssignedEmployee { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TaskListMVC.Models;

namespace TaskListMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TaskListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskListMVC.Models;


namespace TaskListMVC.Controllers
{
    public class TaskListController : Controller
    {

        private readonly TaskListContext _context;
        public TaskListController(TaskListContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<ToDoItems> ToDoList = _context.ToDoItems.ToList();
            return View(ToDoList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDoItems item)
        {
            if (ModelState.IsValid)
            {
                _context.ToDoItems.Add(item);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);

        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            ToDoItems item = _context.ToDoItems.Find(Id);
            if(item == null)
            {
                return NotFound();
            }
            return View(item);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {
            ToDoItems item = _context.ToDoItems.Find(Id);
            if(item == null)
            {
                return NotFound();
            }

                _context.ToDoItems.Remove(item);
                _context.SaveChanges();
                return RedirectToAction("Index");
            

        }
        public IActionResult Update(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            ToDoItems item = _context.ToDoItems.Find(Id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ToDoItems item)
        {
            if (ModelState.IsValid)
            {
                _context.ToDoItems.Update(item);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);

        }
        public IActionResult Complete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            ToDoItems item = _context.ToDoItems.Find(Id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Complete(ToDoItems item)
        {
            if (ModelState.IsValid)
            {
                _context.ToDoItems.Update(item);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);

        }


    }

}

Views/Home/Index.cshtml
    <partial name="_LoginPartial" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskListMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskListMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaskList" asp-action="Index">Task Manager</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TaskListMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/TaskList/Complete.cshtml
@model ToDoItems

<form method="post" asp-action="Complete">
    <input asp-for="Id" hidden />

    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Mark Complete</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemDescription"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ItemDescription" class="form-control" value="@Model.ItemDescription" />
                        <span asp-validation-for="ItemDescription" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="DueDate" class="form-control" value="@Model.DueDate" hidden/>
                        <span asp-validation-for="DueDate" class="text-danger"></span>

                    </div>
                    <div class="col-4">
                        <input asp-for="Progress" class="form-control" value="true" hidden/>
                        <span asp-validation-for="Progress" class="text-danger"></span>

                    </div>
                    <div class="col-4">
                        <input asp-for="AssignedEmployee" class="form-control" value="@Model.AssignedEmployee" hidden/>
                        <span asp-validation-for="AssignedEmployee" class="text-danger"></span>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Mark Complete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

Views/TaskList/Create.cshtml
@model ToDoItems

<form method="post" asp-action="Create">

    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemDescription"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="DueDate"></label>
                    </div>

                    <div class="col-3">
                        <label asp-for="AssignedEmployee"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ItemDescription" class="form-control" />
                        <span asp-validation-for="ItemDescription" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="DueDate" class="form-control" />
                        <span asp-validation-for="DueDate" class="text-danger"></span>

                    </div>

                    <div class="col-3">
                        <input asp-for="AssignedEmployee" class="form-control" />
                        <span asp-validation-for="AssignedEmployee" class="text-danger"></span>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

Views/TaskList/Delete.cshtml
@model ToDoItems

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ItemDescription"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="AssignedEmployee"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="ItemDescription" disabled class="form-control" />
                    </div>


                    <div class="col-6">
                        <input asp-for="AssignedEmployee" disabled class="form-control" />

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

Views/TaskList/Index.cshtml
@model List<ToDoItems>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2>Task List</h2>

        </div>
        <div class="col-6">
            <a asp-action="Create" asp-controller="TaskList" class="btn btn-primary">Create New Task</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Item Description</th>
                    <th>Due Date</th>
                    <th>Employee</th>
                    <th>Progress</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ToDoItems item in Model)
                {
                    string tOrF;
                    if(item.Progress == false)
                    {
                        tOrF = "Not Done";
                    }
                    else
                    {
                        tOrF = "Completed";
                    }
                <tr>
                    <td width="35%">@item.ItemDescription</td>
                    <td width="20%">@item.DueDate</td>
                    <td width="15%">@item.AssignedEmployee</td>
                    <td width="10%">@tOrF</td>
                    <td width="10%">
                        <div class="w-150 btn-group" role="group">
                            @if (item.Progress == false)
                            {
                                <a asp-action="Complete" asp-controller="TaskList" asp-route-Id="@item.Id" class="btn btn-success mx-1">Mark Complete</a>
                                <a asp-action="Update" asp-controller="TaskList" asp-route-Id="@item.Id" class="btn btn-primary mx-1">Edit</a>
                            }
                            <a asp-action="Delete" asp-controller="TaskList" asp-route-Id="@item.Id" class="btn btn-danger mx-1">Delete</a>
                        </div>
                    </td>


                </tr>
                }
             </tbody>
        </table> 
    }
    else
    {
        <p>No tasks created yet</p>
    }



</div>

Views/TaskList/Update.cshtml
@model ToDoItems

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden/>

    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Edit Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemDescription"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="DueDate"></label>
                    </div>

                    <div class="col-4">
                        <label asp-for="AssignedEmployee"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ItemDescription" class="form-control" />
                        <span asp-validation-for="ItemDescription" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="DueDate" class="form-control" />
                        <span asp-validation-for="DueDate" class="text-danger"></span>

                    </div>

                    <div class="col-4">
                        <input asp-for="AssignedEmployee" class="form-control" />
                        <span asp-validation-for="AssignedEmployee" class="text-danger"></span>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>